import { SampleVideo } from '../types/video';

export const SAMPLE_VIDEOS: SampleVideo[] = [
  {
    id: 'sample-drama-1',
    title: 'Chinese Short Drama: The Chairman\'s Return (ဇာတ်လမ်းတို အပိုင်း)',
    description: 'Chinese Drama conversational dialogue with emotional shifts and fast-paced confrontation.',
    category: 'Short Drama / ဇာတ်လမ်းတို',
    durationText: '00:28',
    // Using a reliable HTML5 video sample with dialogue/ambient audio
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail: '🎬',
    sampleSubtitles: {
      detected_language: 'Chinese (Mandarin)',
      summary: 'A dramatic confrontation where a character discovers an unexpected secret and demands an honest explanation.',
      segments: [
        {
          index: 1,
          start: '00:00:01,200',
          end: '00:00:04,150',
          source_text: '你为什么到现在才肯说出真相？',
          burmese_text: 'နင်ဘာလို့ အခုမှ အမှန်အတိုင်း ပြောပြတာလဲ?',
          speaker: 'မင်းသား',
        },
        {
          index: 2,
          start: '00:00:04,400',
          end: '00:00:07,800',
          source_text: '我一直都在保护你，你根本就不懂！',
          burmese_text: 'ငါနင့်ကို အမြဲတမ်း ကာကွယ်ပေးနေခဲ့တာ နင်လုံးဝ နားမလည်ဘူး!',
          speaker: 'မင်းသမီး',
        },
        {
          index: 3,
          start: '00:00:08,100',
          end: '00:00:11,350',
          source_text: '保护我？用谎言来保护我吗？',
          burmese_text: 'ကာကွယ်ပေးတယ် ဟုတ်လား? မုသားတွေနဲ့ လာကာကွယ်တာလား?',
          speaker: 'မင်းသား',
        },
        {
          index: 4,
          start: '00:00:11,700',
          end: '00:00:15,000',
          source_text: '如果我不这么做，今天你不可能站在这里。',
          burmese_text: 'ငါသာ ဒီလိုမလုပ်ခဲ့ရင် ဒီနေ့ နင်ဒီနေရာမှာ ရှိနေနိုင်မှာ မဟုတ်ဘူး။',
          speaker: 'မင်းသမီး',
        },
        {
          index: 5,
          start: '00:00:15,300',
          end: '00:00:19,200',
          source_text: '够了！不要再为自己的自私找借口了。',
          burmese_text: 'တော်တော့! နင့်ရဲ့ အတ္တအတွက် ဆင်ခြေတွေ ထပ်မပေးနဲ့တော့။',
          speaker: 'မင်းသား',
        },
      ],
      tiktok_titles: {
        curiosity_hook: 'သူမရဲ့ လျှို့ဝှက်ချက်ကို သိသွားတဲ့အချိန်…',
        emotional_hook: 'ဒီစကားကြားတော့ ရင်ထဲ တကယ် မခံစားနိုင်တော့ဘူး…',
        mystery_hook: 'တကယ်တမ်း နောက်ကွယ်မှာ ဘာတွေ ဖုံးကွယ်ထားခဲ့တာလဲ?',
        story_hook: 'အချစ်နဲ့ မုသားကြားက မထင်မှတ်ထားတဲ့ အမှန်တရားတစ်ခု!',
        viral_hook: 'ဒီတစ်ခါတော့ သူလုံးဝ မလွတ်တော့ဘူး!',
      },
      hashtags: [
        '#MyanmarSubtitle',
        '#ChineseDrama',
        '#DramaRecap',
        '#ဇာတ်လမ်းတို',
        '#မြန်မာစာတန်းထိုး',
      ],
    },
  },
  {
    id: 'sample-recap-2',
    title: 'Recap Video: The Mysterious Meeting (ရုပ်ရှင်ဇာတ်ကား တွေ့ဆုံခန်း)',
    description: 'Casual modern dialogue between friends about unexpected news and urgent decisions.',
    category: 'Movie Scene / ရုပ်ရှင်',
    durationText: '00:15',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail: '🍿',
    sampleSubtitles: {
      detected_language: 'English',
      summary: 'Two friends meet urgently at a cafe to discuss a life-changing opportunity.',
      segments: [
        {
          index: 1,
          start: '00:00:01,000',
          end: '00:00:03,500',
          source_text: 'Hey, did you see the announcement this morning?',
          burmese_text: 'ဟေ့ရောင်၊ မနက်က ကြေညာချက်ကို နင်တွေ့ပြီးပြီလား?',
          speaker: 'Friend A',
        },
        {
          index: 2,
          start: '00:00:03,800',
          end: '00:00:06,400',
          source_text: 'Yeah, I could hardly believe my eyes.',
          burmese_text: 'အေး၊ ငါတောင် ကိုယ့်မျက်စိကိုယ် မယုံနိုင်ဘူး။',
          speaker: 'Friend B',
        },
        {
          index: 3,
          start: '00:00:06,700',
          end: '00:00:10,200',
          source_text: 'We have to move fast before everyone else finds out.',
          burmese_text: 'တခြားလူတွေ မသိခင် ငါတို့ မြန်မြန်လှုပ်ရှားမှ ဖြစ်မယ်။',
          speaker: 'Friend A',
        },
        {
          index: 4,
          start: '00:00:10,500',
          end: '00:00:14,000',
          source_text: 'Count me in. Let us get to work right now.',
          burmese_text: 'ငါလည်း ပါတယ်။ အခုပဲ စလိုက်ကြရအောင်။',
          speaker: 'Friend B',
        },
      ],
      tiktok_titles: {
        curiosity_hook: 'မနက်ခင်းမှာ သူတို့နှစ်ယောက် ဘာသတင်းကြားလိုက်ရတာလဲ?',
        emotional_hook: 'အချိန်မီ မလုပ်နိုင်ရင် အရာအားလုံး ဆုံးရှုံးရတော့မယ်…',
        mystery_hook: 'သူတို့ လျှို့ဝှက်ကြံစည်နေတဲ့ အစီအစဉ်က ဘာလဲ?',
        story_hook: 'ဘဝကို ပြောင်းလဲစေမယ့် ရွှေအခွင့်အရေးတစ်ခု!',
        viral_hook: 'နောက်ကျသွားရင် လုံးဝ အခွင့်အရေး မရှိတော့ဘူး!',
      },
      hashtags: [
        '#MyanmarSubtitle',
        '#MovieRecap',
        '#TikTokDrama',
        '#ရုပ်ရှင်အညွှန်း',
        '#မြန်မာစာတန်းထိုး',
      ],
    },
  },
];
